# Make a compiler variable, named CC

# Make a compiler variable for C++ 11 standard flag named FLAGS

# Append the "all warnings" flag to variable

# Create LINK variable to compile, assemble, link, and name

# Create variable COMPILE to compile, assemble, but not link

# prob1 rule
#	Dependencies: cereal_oz_to_ton.cc
#   Command: LINK
#   Executable file name: left side reference, $@
#   Input file(s): right side reference, $^


# prob2 rule
#	Dependencies: calc_back_pay.cc
#   Command: LINK
#   Executable file name: left side reference, $@
#   Input file(s): right side reference, $^


# prob3 rule
#	Dependencies: calc_sqr_root.cc
#   Command: LINK
#   Executable file name: left side reference, $@
#   Input file(s): right side reference, $^


# prob4 rule
#	Dependencies: calc_caff_death.cc
#   Command: LINK
#   Executable file name: left side reference, $@
#   Input file(s): right side reference, $^


# Create a rule to clean up object and executable files.
# Dependencies: none
#   Command: rm (make rm silent)
#   Files: prob*
